### ISSUE TITLE
Add break condition

### ISSUE THREAD

**Issue by bormansquirrel** [chinenyeze/api-tests-lib#22]
https://github.com/chinenyeze/api-tests-lib/blob/58a8668185c26f939b25fbc062d14edb5d1b97d1/src/main/java/com/perkbox/util/SuiteListener.java#L19

I think it would be interesting to add a break condition in this loop, otherwise if the service is not available it will take forever

**Comment by chinenyeze** [comment]
Fixed (L19 and L30-33). Added a 20s break condition to the loop. Furthermore, the unsuccessful health check would print an appropriate error and exit the program.

Thanks for point that out.
